### ISSUE TITLE
Missing contributers

### ISSUE THREAD

**Issue by 927589452** [qbi/radioinsecurity#1]
Suggestion:
Add a contributers file

**Comment by qbi** [comment]
Es gibt jetzt eine Datei, siehe https://github.com/qbi/radioinsecurity/commit/1c984d407215099ad1315abb9154a17afeaf0cfc
Die ist im wesentlichen leer. Ich will erst die Mitwirkenden befragen, ob sie gern in der Datei stehen wollen. Falls du magst, kannst du dich gern eintragen.
